"""Land generation — 5 basic lands + (optionally) one investigated dual land.

The `lands` stage does two things: (1) write the 5 basic lands with set-flavored
text, and (2) run a single LLM **investigation** of the set's mana fixing that adds
**one** from-scratch rare dual/fixing land *only when* a real gap remains. Fixing is
decided in three places, in order — reserved **cycles** in the skeleton step (e.g. a
guildgate cycle, now generated by card-gen), mana-fixing **reprints** chosen in the
reprint step, and finally this investigation as the last word. It is given visibility
into the first two so the bonus dual is a genuine top-up, not a duplicate.

Land *cycles* are no longer generated here — they're ordinary cycle members in the
skeleton and are designed by card-gen alongside every other card.

Uses two cheap calls on the active project's ``lands`` model (Haiku/local Gemma).
"""

from __future__ import annotations

import json
import logging
import random
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

from mtgai.generation.llm_client import cost_from_result, generate_with_tool
from mtgai.generation.reprint_selector import (
    _load_set_context,
    _load_slot_texts,
    _read_json,
    extract_set_config,
)
from mtgai.io.atomic import atomic_write_text
from mtgai.models.card import Card
from mtgai.models.enums import Color, Rarity
from mtgai.runtime import ai_lock

logger = logging.getLogger(__name__)

BASICS = [
    {"name": "Plains", "subtype": "Plains", "color_identity": Color.WHITE, "cn": "L-01"},
    {"name": "Island", "subtype": "Island", "color_identity": Color.BLUE, "cn": "L-02"},
    {"name": "Swamp", "subtype": "Swamp", "color_identity": Color.BLACK, "cn": "L-03"},
    {"name": "Mountain", "subtype": "Mountain", "color_identity": Color.RED, "cn": "L-04"},
    {"name": "Forest", "subtype": "Forest", "color_identity": Color.GREEN, "cn": "L-05"},
]


# ---------------------------------------------------------------------------
# Task 1: basic land flavor text
# ---------------------------------------------------------------------------


def _build_basics_prompt(set_config: dict, context: dict[str, str]) -> tuple[str, str]:
    system = (
        "You are a Magic: The Gathering creative writer and art director. You write "
        "evocative, setting-appropriate basic-land art briefs and (sparingly) flavor text."
    )
    # The setting prose + constraints come from the shared context blocks (read from
    # theme.json), NOT the skeleton config's legacy theme/flavor_description fields —
    # those are empty for theme.json-driven sets, which left this prompt blank.
    user = (
        f"# Basic Lands for {set_config.get('name', 'Unknown')}\n\n"
        "## Setting\n"
        f"{context['setting']}\n\n"
        "## Constraints\n"
        f"{context['constraints']}\n\n"
        "Modern sets print several ALTERNATE ARTS of each basic land — different vistas "
        "of the same world. For EACH of the five basic land types (Plains, Island, Swamp, "
        "Mountain, Forest), give:\n\n"
        "1. **art_scenes** — exactly 4 DISTINCT one-sentence art briefs. Each is a "
        "different location, landmark, weather, or time of day in THIS world and becomes "
        "one alternate printing, so make them visually distinct from one another. "
        "Panoramic and concrete, NO figures or characters, evoke a specific place. Match "
        "the terrain to the type (Plains = open/flat, Island = water/coast, Swamp = "
        "dark/decaying, Mountain = volcanic/rocky, Forest = overgrown wilderness).\n"
        "2. **flavor_text** — ONE short (1 sentence) flavor text for the type. Most "
        "printings carry no flavor, so make this one quotable and in-world; use an "
        "em-dash for attribution if quoting a character.\n"
    )
    return system, user


def _build_basics_tool_schema() -> dict:
    return {
        "name": "create_basic_lands",
        "description": "Provide alternate-art briefs + one flavor text for the 5 basic land types",
        "input_schema": {
            "type": "object",
            "properties": {
                "basics": {
                    "type": "array",
                    "description": (
                        "One entry per basic land type (Plains, Island, Swamp, Mountain, Forest)"
                    ),
                    "items": {
                        "type": "object",
                        "properties": {
                            "land_name": {
                                "type": "string",
                                "description": "Plains, Island, Swamp, Mountain, or Forest",
                            },
                            "art_scenes": {
                                "type": "array",
                                "description": (
                                    "4 distinct one-sentence art briefs (alternate arts) "
                                    "for this land type"
                                ),
                                "items": {"type": "string"},
                            },
                            "flavor_text": {
                                "type": "string",
                                "description": "One flavor text for this type (used on a single "
                                "printing)",
                            },
                        },
                        "required": ["land_name", "art_scenes", "flavor_text"],
                    },
                },
            },
            "required": ["basics"],
        },
    }


# ---------------------------------------------------------------------------
# Task 2: investigate the set's fixing, add one bonus dual only if needed
# ---------------------------------------------------------------------------


def _load_reprint_summary(asset: Path) -> str:
    """One line per chosen reprint (name · type_line · role) for the investigation
    prompt — the full placed-reprint list, so the model can judge which (if any)
    supply mana fixing (Evolving Wilds, taplands, fetch-a-basic ramp…) and which are
    just removal/creatures. Graceful when ``reprint_selection.json`` is absent/empty —
    the reprints stage may have been skipped."""
    data = _read_json(asset / "reprint_selection.json", {})
    selections = data.get("selections") if isinstance(data, dict) else None
    lines: list[str] = []
    for sel in selections or []:
        if not isinstance(sel, dict):
            continue
        cand = sel.get("candidate") or {}
        name = str(cand.get("name") or "").strip()
        if not name:
            continue
        bits = " · ".join(p for p in (cand.get("type_line", ""), cand.get("role", "")) if p)
        lines.append(f"- {name}" + (f" ({bits})" if bits else ""))
    if not lines:
        return "(no reprints were chosen for this set — assume no reprint-based fixing)"
    return "\n".join(lines)


def _build_investigation_prompt(
    set_config: dict,
    context: dict[str, str],
    slot_texts: list[dict[str, str]],
    reprint_summary: str,
) -> tuple[str, str]:
    """The set's full context + every unfilled slot + the chosen reprints → decide
    whether to add ONE bonus rare dual land. Reuses the shared skeleton-block
    formatters (via ``context``) so this judges the set the same way the relabel did.
    Multicolor density is read from the slot prose, not stale structured fields."""
    system = (
        "You are a Magic: The Gathering set designer making the FINAL call on a set's "
        "mana fixing. Fixing in a set comes from three sources, in order: (1) reserved "
        "land/card CYCLES in the skeleton (e.g. a guildgate cycle), (2) mana-fixing "
        "REPRINTS chosen from a staple pool (Evolving Wilds, taplands, etc.), and (3) "
        "you — a single bespoke BONUS land that tops up only if the first two left a "
        "gap.\n\n"
        "Your job: look at the whole set and decide whether it needs ONE extra "
        "dual/fixing land. Add one ONLY IF a real multicolor-fixing gap remains after "
        "the cycles and reprints above, OR the set has a strong multicolor theme that "
        "justifies a marquee dual on top. If the set already has adequate fixing, or is "
        "mostly mono-color, decline — do not add a redundant land.\n\n"
        "If you add one, design it as a RARE: a premium, setting-appropriate dual that "
        "need NOT enter tapped (it is a deliberate bonus, not baseline Limited fixing). "
        "Give it a setting-appropriate but generic name (no character names) and a "
        "one-sentence flavor text. Return your decision through the tool only."
    )

    slot_lines = "\n".join(f"{s['slot_id']}: {s['text']}" for s in slot_texts) or "(no slots)"
    user = (
        f"# Fixing investigation — {set_config.get('name', 'Unknown')}\n\n"
        "## Set theme\n"
        f"{context['setting']}\n\n"
        "## Mechanics\n"
        f"{context['mechanics']}\n\n"
        "## Draft archetypes\n"
        f"{context['archetypes']}\n\n"
        "## Constraints\n"
        f"{context['constraints']}\n\n"
        "## Reprints already placed in this set\n"
        "These staples already occupy skeleton slots — judge which of them (if any) "
        "supply mana fixing, and treat the rest as ordinary cards:\n"
        f"{reprint_summary}\n\n"
        f"## Unfilled skeleton slots ({len(slot_texts)})\n"
        "Reprint-claimed slots are excluded (see above). Land cycles reserved in the "
        "skeleton (e.g. guildgates) appear here as land slots; judge multicolor "
        "density and existing fixing from these descriptors.\n"
        f"{slot_lines}\n\n"
        "Decide: does this set need one bonus rare dual land on top of the fixing "
        "above? If yes, design it."
    )
    return system, user


def _build_investigation_tool_schema() -> dict:
    return {
        "name": "investigate_fixing",
        "description": "Decide whether the set needs one bonus dual land, and design it if so.",
        "input_schema": {
            "type": "object",
            "properties": {
                "needs_dual_land": {
                    "type": "boolean",
                    "description": "True only if a real fixing gap remains, or a "
                    "strong multicolor theme justifies a marquee dual.",
                },
                "reasoning": {
                    "type": "string",
                    "description": "Why the set does or does not need a bonus dual, citing the "
                    "existing cycle/reprint fixing.",
                },
                "dual_land": {
                    "type": "object",
                    "description": "The bonus rare dual land — provide ONLY when "
                    "needs_dual_land is true.",
                    "properties": {
                        "name": {"type": "string"},
                        "type_line": {"type": "string", "description": "e.g. 'Land'"},
                        "oracle_text": {"type": "string"},
                        "flavor_text": {"type": "string"},
                    },
                    "required": ["name", "type_line", "oracle_text", "flavor_text"],
                },
            },
            "required": ["needs_dual_land", "reasoning"],
        },
    }


# ---------------------------------------------------------------------------
# Card builders
# ---------------------------------------------------------------------------


def _make_basic_card(
    basic: dict, flavor_text: str, set_code: str, collector_number: str, scene: str = ""
) -> Card:
    """One basic-land printing. ``scene`` is the alternate's art brief, stored in
    ``design_notes`` so the art-prompt stage (which feeds design_notes to the LLM)
    renders a distinct vista per alternate."""
    notes = f"Alternate basic land art — {scene}" if scene else "Basic land"
    return Card(
        name=basic["name"],
        mana_cost=None,
        cmc=0.0,
        colors=[],
        color_identity=[basic["color_identity"]],
        type_line=f"Basic Land — {basic['subtype']}",
        supertypes=["Basic"],
        card_types=["Land"],
        subtypes=[basic["subtype"]],
        oracle_text="",
        flavor_text=flavor_text,
        collector_number=collector_number,
        rarity=Rarity.COMMON,
        set_code=set_code,
        is_reprint=True,
        design_notes=notes,
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    )


def _make_nonbasic_card(data: dict, set_code: str) -> Card:
    """Build the bonus dual land from the investigation's design. A from-scratch
    RARE (``is_reprint=False``); ``color_identity`` is inferred from the mana
    symbols in its oracle text."""
    ci: list[Color] = []
    color_map = {
        "{W}": Color.WHITE,
        "{U}": Color.BLUE,
        "{B}": Color.BLACK,
        "{R}": Color.RED,
        "{G}": Color.GREEN,
    }
    for symbol, color in color_map.items():
        if symbol in data["oracle_text"]:
            ci.append(color)

    return Card(
        name=data["name"],
        mana_cost=None,
        cmc=0.0,
        colors=[],
        color_identity=ci,
        type_line=data["type_line"],
        supertypes=[],
        card_types=["Land"],
        subtypes=[],
        oracle_text=data["oracle_text"],
        flavor_text=data["flavor_text"],
        collector_number="L-06",
        rarity=Rarity.RARE,
        set_code=set_code,
        is_reprint=False,
        design_notes="Bonus rare dual/fixing land added by the lands investigation",
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    )


def _slugify(name: str) -> str:
    return name.lower().replace(" ", "_").replace("'", "").replace(",", "")


# ---------------------------------------------------------------------------
# Stage entry point
# ---------------------------------------------------------------------------


def generate_lands(
    on_call_start: Callable[[str], None] | None = None,
    on_card_saved: Callable[[Card], None] | None = None,
) -> dict:
    """Generate land cards for the active project: 2-4 alternate-art printings per
    basic type, plus one investigated bonus dual land if the set's fixing needs it.

    Returns a summary dict with ``total_cards`` and ``cost_usd``.

    Optional callbacks let a UI surface progress:
      ``on_call_start(model)`` fires before each AI request (basics, then
      investigation), ``on_card_saved(card)`` fires after each Card is written.
    """
    from mtgai.io.asset_paths import set_artifact_dir
    from mtgai.runtime.active_project import require_active_project

    project = require_active_project()
    set_code = project.set_code
    set_dir = set_artifact_dir()
    skeleton_path = set_dir / "skeleton.json"
    cards_dir = set_dir / "cards"
    cards_dir.mkdir(parents=True, exist_ok=True)

    # Clear this stage's prior output first. The lands stage owns the ``L-*`` cards
    # (basics + dual); card-gen's land cycles use numeric collector numbers, so the
    # ``L-*`` glob never touches them. Without this, a re-run (e.g. via the edit
    # cascade) would leave stale alternates behind — the random per-type count and
    # lettered numbers (L-01a/b/c) mean a fresh run won't overwrite the old ones.
    for stale in cards_dir.glob("L-*.json"):
        stale.unlink()

    set_config = extract_set_config(skeleton_path)
    # Shared set-context blocks (setting prose / constraints / mechanics / archetypes)
    # read from theme.json — used by BOTH the basics call and the fixing investigation
    # so each judges the same set framing the skeleton relabel saw.
    context = _load_set_context(set_dir, set_config)
    model_id = project.settings.get_llm_model_id("lands")
    # Route both LLM transcripts (JSONL + HTML) beside the stage artifacts, like
    # every other stage (mechanics/logs, reprints/logs, …) — omitting log_dir
    # would dump them into llmfacade's session dirs under backend/logs/.
    log_dir = set_dir / "lands" / "logs"

    logger.info("Generating lands for set %s...", set_code)

    cards_saved = 0
    cost = 0.0

    # (1) Basic land flavor — one call.
    system, user = _build_basics_prompt(set_config, context)
    if on_call_start is not None:
        on_call_start(model_id)
    response = generate_with_tool(
        system_prompt=system,
        user_prompt=user,
        tool_schema=_build_basics_tool_schema(),
        model=model_id,
        temperature=0.7,
        # 5 land types x (4 one-sentence art briefs + 1 flavor) is a lot of JSON;
        # at 2048 the (often verbose, local) model truncated mid-output
        # (finish: length) around the 3rd type. 4096 fits all five with headroom.
        max_tokens=4096,
        log_dir=log_dir,
    )
    basics_data = response.get("result", {}).get("basics", [])
    cost += cost_from_result(response)
    logger.info(
        "Basics tokens: in=%s out=%s",
        response.get("input_tokens", "?"),
        response.get("output_tokens", "?"),
    )

    by_name = {str(b.get("land_name", "")): b for b in basics_data if isinstance(b, dict)}
    for basic in BASICS:
        data = by_name.get(basic["name"], {})
        scenes = [str(s).strip() for s in (data.get("art_scenes") or []) if str(s).strip()]
        flavor = str(data.get("flavor_text") or "").strip()

        # 2-4 alternate-art printings per basic type (modern-set style). The count
        # is random per type, capped by how many distinct scenes the model gave us.
        count = random.randint(2, 4)
        if scenes:
            count = min(count, len(scenes))
        else:
            logger.warning("No art scenes for %s; emitting a single plain basic", basic["name"])
            scenes, count = [""], 1

        for j in range(count):
            # Flavor on at most ONE printing per type (the first); the rest are
            # flavorless — basics rarely carry flavor text.
            variant_flavor = flavor if j == 0 else ""
            cn = f"{basic['cn']}{chr(ord('a') + j)}"  # L-01a, L-01b, …
            card = _make_basic_card(basic, variant_flavor, set_code, cn, scenes[j])
            filename = f"{cn}_{_slugify(basic['name'])}.json"
            atomic_write_text(
                cards_dir / filename,
                json.dumps(card.model_dump(mode="json"), indent=2, ensure_ascii=False),
            )
            cards_saved += 1
            logger.info("  Saved %s alt %s: %s", basic["name"], cn, filename)
            if on_card_saved is not None:
                on_card_saved(card)

    # Honor a Cancel between the two LLM calls — an in-flight call can't be
    # interrupted, so we stop at this boundary. The basics already written persist;
    # the guarded endpoint reads ``ai_lock.is_cancelled()`` to skip the success-heal.
    if ai_lock.is_cancelled():
        logger.warning(
            "Land generation CANCELLED by user after basics (%d cards saved)", cards_saved
        )
        return {"total_cards": cards_saved, "cost_usd": cost, "cancelled": True}

    # (2) Investigate the set's fixing across all three sources, add one bonus
    # rare dual land only if a real gap remains. Reuses the ``context`` loaded above.
    # Exclude reprint-stamped slots: the reprint stage already claimed them (they're
    # listed separately as "reprints placed"), so they're no longer unfilled.
    slot_texts = _load_slot_texts(skeleton_path, include_reprints=False)
    reprint_summary = _load_reprint_summary(set_dir)
    inv_system, inv_user = _build_investigation_prompt(
        set_config, context, slot_texts, reprint_summary
    )
    if on_call_start is not None:
        on_call_start(model_id)
    inv_result: dict = {}
    try:
        inv_response = generate_with_tool(
            system_prompt=inv_system,
            user_prompt=inv_user,
            tool_schema=_build_investigation_tool_schema(),
            model=model_id,
            temperature=0.7,
            # Smaller output (one dual + reasoning), but a truncated tool-call JSON
            # fails to parse just the same — give the same headroom as the basics call.
            max_tokens=4096,
            log_dir=log_dir,
        )
        cost += cost_from_result(inv_response)
        inv_result = inv_response.get("result", {}) or {}
    except Exception:
        logger.exception("Land fixing investigation failed; adding no bonus dual")

    dual = inv_result.get("dual_land")
    reasoning = str(inv_result.get("reasoning") or "").strip()
    if inv_result.get("needs_dual_land") and isinstance(dual, dict) and dual.get("name"):
        card = _make_nonbasic_card(dual, set_code)
        filename = f"L-06_{_slugify(dual['name'])}.json"
        atomic_write_text(
            cards_dir / filename,
            json.dumps(card.model_dump(mode="json"), indent=2, ensure_ascii=False),
        )
        cards_saved += 1
        if on_card_saved is not None:
            on_card_saved(card)
        logger.info("  Added bonus dual land: %s — %s", dual["name"], reasoning)
    else:
        logger.info("Investigation declined a bonus dual land: %s", reasoning or "(no reason)")

    logger.info("Generated %d land cards ($%.4f)", cards_saved, cost)
    return {"total_cards": cards_saved, "cost_usd": cost}
